name: EES CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]


    steps:

    - name: Set up JDK 11.0.2
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.2'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: cache-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: cache-${{ runner.os }}-m2

    - name: Clone agentsoz/ees
      uses: actions/checkout@v2
      with:
        repository: agentsoz/ees
        path: ees

    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: cd ees && git submodule update --init --recursive

    - name: Add write permissions to clone
      run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE/ees

    - name: List all cloned repositories
      run: |
        echo $GITHUB_WORKSPACE
        ls -la $GITHUB_WORKSPACE

    - name: Build agentsoz/ees
      run: |
        mvn -v
        cd ees && mvn package -B -Dmatsim.preferLocalDtds=true && cd -
        mkdir staging && cp ees/ees/target/*.zip staging

    - name: Upload EES build artifacts
      uses: actions/upload-artifact@v2
      with:
        path: staging
